steps:
  - name: ":docker: :package:"
    plugins:
      docker-compose#v1.5.2:
        build: probot-app-license
        image-repository: 296822479253.dkr.ecr.us-east-2.amazonaws.com/fusionjs
  - wait
  - name: ":eslint:"
    command: "npm run lint"
    plugins:
      docker-compose#v1.5.2:
        run: probot-app-license
  - name: ":jest:"
    command: "npm run jest"
    plugins:
      docker-compose#v1.5.2:
        run: probot-app-license
